# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "GuideDogs.xcodeproj")
    gym(
      verbose: true,
      workspace: "GuideDogs.xcworkspace",
      scheme: "Soundscape",
      clean: true,
      configuration: "Release",
      output_name: "Soundscape",
      export_xcargs: "-allowProvisioningUpdates",
      skip_profile_detection: true,
      export_options: {
        method: "app-store",
        signingStyle: "manual",
        provisioningProfiles: {
          "services.soundscape": "match AppStore services.soundscape"
        }
      }
    )
    upload_to_testflight(
      username: "benjamint@okeenea.com",
      app_identifier: "services.soundscape",
    )
  end
end
